In [3]:
import numpy as np

## create array using numpy
##create a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [6]:
arr2 = np.array([1, 2, 3, 4, 5, 6])
arr2.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [8]:
arr2=np.array([[1, 2, 3, 4, 5, 6],[2,3,4,5,6,7]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5 6]
 [2 3 4 5 6 7]]
(2, 6)


In [10]:
np.arange(0,10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# Numpy Vectorize Operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print("Addition:", arr1 + arr2 )

print("Subtraction:", arr1 - arr2 )
print("Multiplication:", arr1 * arr2 )
print("Division:", arr1 / arr2 )

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [18]:
#Universal Function
arr = np.array([2,3,4,5,6])
print("Square root:", np.sqrt(arr))

print("Exponential:", np.exp(arr))

print("Logarithm:", np.log(arr))

print("Sine:", np.sin(arr))

Square root: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential: [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Logarithm: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
Sine: [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [19]:
## array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array:\n", arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
print(arr[0][0])
print(arr[0:2,2:])


1
[[3 4]
 [7 8]]


In [27]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [24]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [28]:
## Modify array elements
arr[0][0]=100
print(arr)


[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [29]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [31]:
## Statistical concepts - Normalization
# to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

#Calculating mean and standard deviation
mean = np.mean(data)
std = np.std(data)

# Normalizing the data
normalized_data = (data - mean) / std
print("Normalized Data:", normalized_data)


Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [35]:
# Logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10])

data [(data>=5) & (data<=8)]

array([5, 6, 7, 8])